version: '3'

services:
    load_balancer:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./load-balancer/nginx.conf:/etc/nginx/nginx.conf
      networks:
        - rede-compose
      depends_on:
        - site1
        - site2
        - site3
      
    site1:
      image: natasilva/nginx_server_ra2027:branco
      networks:
        - rede-compose
    
    site2:
      image: natasilva/nginx_server_ra2027:verde
      networks:
        - rede-compose
    
    site3:
      image: natasilva/nginx_server_ra2027:azul
      networks:
        - rede-compose

networks:
  rede-compose:
    driver: bridge